name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        AWS_REGION: ap-southeast-2
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: copy to S3
      run: aws s3 sync index.html s3://${{ secrets.AWS_S3_BUCKET }}
        
